#pragma once

#include <pebble.h>

#define SMALL_FONT FONT_KEY_GOTHIC_24_BOLD
#define DEFAULT_FONT FONT_KEY_GOTHIC_28

#define MARGIN 4

#define DEFAULT_WIDTH layer_get_bounds(window_layer).size.w
#define DEFAULT_HEIGHT 28

#define TIME_LEFT 0
#define TIME_TOP PBL_IF_ROUND_ELSE(6, 1)
#define TIME_WIDTH DEFAULT_WIDTH
#define TIME_HEIGHT DEFAULT_HEIGHT
#define TIME_FONT FONT_KEY_GOTHIC_18
#define TIME_ALIGN GTextAlignmentCenter

#define SERVICE_STATUS_LEFT 0
#define SERVICE_STATUS_TOP PBL_IF_ROUND_ELSE(27, 21)
#define SERVICE_STATUS_WIDTH DEFAULT_WIDTH
#define SERVICE_STATUS_HEIGHT DEFAULT_HEIGHT
#define SERVICE_STATUS_FONT SMALL_FONT
#define SERVICE_STATUS_ALIGN GTextAlignmentCenter

#define EVE_TIME_LEFT 0
#define EVE_TIME_TOP PBL_IF_ROUND_ELSE(71, 65)
#define EVE_TIME_WIDTH DEFAULT_WIDTH
#define EVE_TIME_HEIGHT DEFAULT_HEIGHT
#define EVE_TIME_FONT DEFAULT_FONT
#define EVE_TIME_ALIGN GTextAlignmentCenter

#define USER_COUNT_LEFT 0
#define USER_COUNT_TOP PBL_IF_ROUND_ELSE(116, 110)
#define USER_COUNT_WIDTH DEFAULT_WIDTH
#define USER_COUNT_HEIGHT DEFAULT_HEIGHT
#define USER_COUNT_FONT DEFAULT_FONT
#define USER_COUNT_ALIGN GTextAlignmentCenter

#define MARKET_ITEM_DESC_LEFT PBL_IF_ROUND_ELSE(44, 27)
#define MARKET_ITEM_DESC_TOP PBL_IF_ROUND_ELSE(55, 49) 
#define MARKET_ITEM_DESC_WIDTH 57
#define MARKET_ITEM_DESC_HEIGHT DEFAULT_HEIGHT
#define MARKET_ITEM_DESC_FONT FONT_KEY_GOTHIC_18
#define MARKET_ITEM_DESC_ALIGN GTextAlignmentCenter

#define MARKET_ITEM_VALUE1_LEFT PBL_IF_ROUND_ELSE(101, 84)
#define MARKET_ITEM_VALUE1_TOP PBL_IF_ROUND_ELSE(55, 49) 
#define MARKET_ITEM_VALUE1_WIDTH 57
#define MARKET_ITEM_VALUE1_HEIGHT DEFAULT_HEIGHT
#define MARKET_ITEM_VALUE1_FONT FONT_KEY_GOTHIC_18
#define MARKET_ITEM_VALUE1_ALIGN GTextAlignmentCenter

#define MARKET_ITEM_VALUE2_LEFT PBL_IF_ROUND_ELSE(44, 27)
#define MARKET_ITEM_VALUE2_TOP PBL_IF_ROUND_ELSE(99, 93) 
#define MARKET_ITEM_VALUE2_WIDTH 57
#define MARKET_ITEM_VALUE2_HEIGHT DEFAULT_HEIGHT
#define MARKET_ITEM_VALUE2_FONT FONT_KEY_GOTHIC_18
#define MARKET_ITEM_VALUE2_ALIGN GTextAlignmentCenter

#define MARKET_ITEM_VALUE3_LEFT PBL_IF_ROUND_ELSE(101, 84)
#define MARKET_ITEM_VALUE3_TOP PBL_IF_ROUND_ELSE(99, 93) 
#define MARKET_ITEM_VALUE3_WIDTH 57
#define MARKET_ITEM_VALUE3_HEIGHT DEFAULT_HEIGHT
#define MARKET_ITEM_VALUE3_FONT FONT_KEY_GOTHIC_18
#define MARKET_ITEM_VALUE3_ALIGN GTextAlignmentCenter

