#pragma once

#include <pebble.h>

#define DEFAULT_FONT FONT_KEY_GOTHIC_28

#define MARGIN 4

#define DEFAULT_WIDTH layer_get_bounds(window_layer).size.w
#define DEFAULT_HEIGHT 28

#define TIME_LEFT 0
#define TIME_TOP PBL_IF_ROUND_ELSE(6, 1)
#define TIME_WIDTH DEFAULT_WIDTH
#define TIME_HEIGHT DEFAULT_HEIGHT
#define TIME_FONT FONT_KEY_GOTHIC_18
#define TIME_ALIGN GTextAlignmentCenter

#define EVE_TIME_LEFT 0
#define EVE_TIME_TOP PBL_IF_ROUND_ELSE(71, 65)
#define EVE_TIME_WIDTH DEFAULT_WIDTH
#define EVE_TIME_HEIGHT DEFAULT_HEIGHT
#define EVE_TIME_FONT DEFAULT_FONT
#define EVE_TIME_ALIGN GTextAlignmentCenter

#define USER_COUNT_LEFT 0
#define USER_COUNT_TOP PBL_IF_ROUND_ELSE(116, 110)
#define USER_COUNT_WIDTH DEFAULT_WIDTH
#define USER_COUNT_HEIGHT DEFAULT_HEIGHT
#define USER_COUNT_FONT DEFAULT_FONT
#define USER_COUNT_ALIGN GTextAlignmentCenter

#define SERVICE_STATUS_LEFT 0
#define SERVICE_STATUS_TOP PBL_IF_ROUND_ELSE(27, 21)
#define SERVICE_STATUS_WIDTH DEFAULT_WIDTH
#define SERVICE_STATUS_HEIGHT DEFAULT_HEIGHT
#define SERVICE_STATUS_FONT DEFAULT_FONT
#define SERVICE_STATUS_ALIGN GTextAlignmentCenter